### ISSUE TITLE
Can't set event.start and event.end on empty instantiated event object 

### ISSUE THREAD

**Issue by jhatch28** [nylas/nylas-nodejs#201]
I'm opening this issue on behalf of someone developing an integration to Nylas with this SDK. 
It appears that the code is a no-op if there isn't already a `when` attribute set on the event. 
Is this the expected behavior?

I think I have a bug in the Nylas Node SDK or an incongruency of the API reference. I have successfully retrieved an account's primary calendar and listed events on an account's primary calendar, so auth and crud is fine. However, in one particular case, I am not able to create an event using the Node SDK due to usage of the start / end attributes instead of the nested objects of the when attribute on the event object.

Here is the snippet:
```
  let event = nylas.events.build();
  ...
  event.start = parseInt((new Date(calendarEntry.start).getTime() / 1000).toFixed(0)); // convert to unix timestamp
  event.end = parseInt((new Date(calendarEntry.end).getTime() / 1000).toFixed(0));
  console.log(event);
  // outputs the event object but without the start / end attributes, everything else accepts sets fine
  event.save({ notify_participants: false });
```

Here is the error
`Error: Must specify 'when' when creating an event.`

I was hoping to use the cleaner start / end attributes rather than the nested when objects. I will try with the nested when objects instead.

**Comment by lkaileh** [comment]
My understanding is that the API requires the `when` subobject for any event created.  All the events endpoints require it in Postman.  That said, I can see how there is a case for simplifying that via the SDK since the SDK is supposed to make integrating easier that directly with the API.  I think maybe this is something @Gerdie can tackle if the product team agrees the SDK should move in this direction.  @philrenaud tagging you here in case this is something that comes down the pipe while I'm on leave.

**Comment by jhatch28** [comment]
The code [here](https://github.com/nylas/nylas-nodejs/blob/main/src/models/event.ts#L31) has getters and setters for start and end that only work if there's already a `when` object on the event. So it works for events that come back from the API, but not for  freshly instantiated events.
