### ISSUE TITLE
Error when updating an event 

### ISSUE THREAD

**Issue by aballester92** [nylas/nylas-nodejs#211]
I'm trying to update an event with the SDK and keep running into - `TypeError: event.save is not a function`. There is a workaround but I don't believe it's how it's intended to work. 

The code I'm running when erroring:
```
event = nylas.events.find('4qy0dz8csdho3rdhofopqcq2k') 
event.title = 'node sdk update test';
event.location = 'wherever';
event.description = 'Let\'s make sure this posts to my cal';
event.busy = false;
event.calendarId='e4xxih4e9urzgfxce9wgcuxdg';
event.participants = [{name: 'AB', email: 'aballesterse@gmail.com'}];
event.when = {start_time: 1609988407, end_time: 1609990207};
event.save({notify_participants: true}).then(event => console.log(event)).catch(err => console.log(err))
```

Working code: 
```
event = nylas.events.find('4qy0dz8csdho3rdhofopqcq2k').then(ev => {
  console.log(ev)
  ev.title = 'node sdk update test';
  ev.location = 'wherever';
  ev.description = 'Let\'s make sure this posts to my cal';
  ev.busy = false;
  ev.calendarId='e4xxih4e9urzgfxce9wgcuxdg';
  ev.participants = [{name: 'AB', email: 'aballesterse@gmail.com'}];
  ev.when = {start_time: 1609988407, end_time: 1609990207};
  ev.save({notify_participants: true}).then(ev2 => console.log('it worked', ev2));
})
```

**Comment by Gerdie** [comment]
Hi @aballester92 this is working as intended. I think your confusion is coming from Promises. Almost all of our Node SDK methods return [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). In your working code, you use `then` to wait for the promise to resolve, and then work with the event it resolves to. In your erroring code, when you wrote `event = nylas.events.find('4qy0dz8csdho3rdhofopqcq2k')` you were assigning the variable `event` to a Promise,  and then assigning properties to the Promise, and then calling `save()` on the Promise, which threw an error because a Promise doesn't have a `save()` function.
