### ISSUE TITLE
Wrong type of Draft files

### ISSUE THREAD

**Issue by KazimirPodolski** [nylas/nylas-nodejs#314]
**Describe the bug**
Draft type has field `files` typed as `FileProperties[]` which contradicts docs e.g. here https://developer.nylas.com/docs/api#post/drafts.
 Or is it possible to provide File object returned by File.upload? It's not clear at all to me.

**To Reproduce**
```typescript
const file = await new File(nylas, { filename, contentType, size, data }).upload();
const draft = new Draft(nylas, { files: ??? });
```
I didn't try to actually make it work.

**Expected behavior**
The type should be `file_ids`'s  `string[]`

**SDK Version:**
6.0.0

**Comment by mrashed-dev** [comment]
Hey @KazimirPodolski thanks for opening this issue! The `files` field differs from the `file_ids` in the API payload. The `files` field, as defined in the `Draft` class is an array of `File` type. The `Draft` class will then parse out the file IDs individually instead of you having to do that work.

In the case of your code sample, it would look like this (although note that you must provide a value for `to` within a `DraftProperties` object):

```js
const file = await new File(nylas, { filename, contentType, size, data }).upload();
const draft = new Draft(nylas, { files: [file] });
```

The following code snippet worked on me for v6.0 which includes all operations from creating the file to creating the draft:

```js
// Read the file and metadata
const fileContents = fs.readFileSync('hello_world.txt', 'utf8');
const fileSize = fs.statSync(filename).size;
fs.unlinkSync(filename);

// Create the `File` object representing the created file
const nylasFile = new File(nylas, {
    filename: 'hello_world.txt',
    data: fileContents,
    contentType: 'text/plain',
    size: fileSize
});

// Upload it to the Nylas API
await nylasFile.upload();

// Create a 
const draft = new Draft(nylas, {to:[{email: 'test@email.com'}], files: [nylasFile]});
```

Don't hesitate to re-open the issue if I didn't answer your question!

**Comment by KazimirPodolski** [comment]
> The `Draft` class will then parse out the file IDs individually instead of you having to do that work.

Actually, to me it looks like more work than less. If `files` field was accepting IDs, then I can use it with both IDs or `File`s (and doing `files.map(({ id }) => id)` is not a work really). But now I have to do extra loading of all files by IDs which I have (because I simply don't need anything but IDs). Not because full `Files` objects are required (API tells it doesn't), but just because Draft class accepts only them.

Moreover, in reality `Upload it to the Nylas API` and `Create a draft` are not in the same method. Because first you upload files from front end through back end to Nylas (as docs tell), then after user is done composing you send the message. So now I have to either reload files by IDs each with it's own request (because there is no GET for list of files by IDs as far as I see), OR send full `File` object back to front end (hoping file contents won't be included, or cleaning them manually), then when making/sending a draft pass this partial `File` to `Draft`.

```typescript
// should be called when user uploads
function uploadFile() {
  // Read the file and metadata
  const fileContents = fs.readFileSync('hello_world.txt', 'utf8');
  const fileSize = fs.statSync(filename).size;
  fs.unlinkSync(filename);
  
  // Create the `File` object representing the created file
  const nylasFile = new File(nylas, {
      filename: 'hello_world.txt',
      data: fileContents,
      contentType: 'text/plain',
      size: fileSize
  });
  
  // Upload it to the Nylas API
  await nylasFile.upload();
}

// should be called when user sends
function createDraft(nylasFile: File???) {
  // Create a 
  const draft = new Draft(nylas, {to:[{email: 'test@email.com'}], files: [nylasFile]});
}
```
Please clarify what's the indended flow here, as API makes perfect sense to me, but SDK not quite.

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thanks for your reply, the intended workflow is like you described -- a user can upload the file they want t osend (resulting in a `File` object), and attach said uploaded `File` to the draft by passing in the `DraftProperties` object.

However, I do see your concern with having _multiple_ file IDs already but just wanting to upload it directly into a `Draft` by just setting the file_ids parameter directly. The issue comes from the fact that the API never returns `file_ids`, even if you create a Draft with `file_ids` set, it will return a Draft object with only `files` which is an array of `File` type not a string of IDs. This can be a little dicey in terms of creating a Draft, then wanting to modify the attachments (add/remove an attached file) before sending it.

I'm going to re-open this issue and investigate the possibility of having `file_ids` exposed and modifiable for `Draft` objects, and I'll keep you up to date on it! 

In the meantime, here's a workaround that could help you in your scenario (it's not pretty but it's much faster than fetching the Files one-by-one):

```js
const Nylas = require('nylas');
Nylas.config({clientId: 'clientId', clientSecret: 'clientSecret'});
const nylas = Nylas.with('access_token');

const fileIds = ['file-id1', 'file-id2', 'file-id3'];
const files: File = [];

for(const id of fileIds) {
  const file = new File(nylas);
  file.id = id;
  files.push(file);
}

const draft = new Draft(nylas, {to:[{email: 'test@email.com'}], files: files});
```

_Technically_ the files provided in the `files` array are not _real_ files, but the way we set `file_ids` it's by extracting only the `id` from the `File` objects in the `files` array. Much faster than needing to fetch one-by-one just to load them in the `Draft`. 

I'll keep you up to date regarding having direct `file_ids` support for `Draft` objects.

**Comment by mrashed-dev** [comment]
@KazimirPodolski Thanks for your patience, I've added a new field in `Draft` that will allow for directly adding file IDs to a Draft. This should be included in the next release. 

Please note that this variable only adds files to a draft, to remove a file it must be done on the files array. Upon saving we will make sure to merge unique values in the outgoing payload.

Here's an example code sample:
```js
const Nylas = require('nylas');
Nylas.config({clientId: 'clientId', clientSecret: 'clientSecret'});
const nylas = Nylas.with('access_token');

const draft = new Draft(nylas, {
  to: [{ name: 'Nylas Swag', email: 'swag@nylas.com' }],
  fileIdsToAttach = ["file_id_1", "file_id_2"],
});
draft.save();
```
