### ISSUE TITLE
Drafts docs inconsistent with Node SDK 6.3.1

### ISSUE THREAD

**Issue by ederski** [nylas/nylas-nodejs#347]
**Describe the bug**
The Node SDK code sample in the [Draft docs](https://developer.nylas.com/docs/api/#post/drafts) has a type error (and a syntax error). Also the code sample in the [v6 migration guide](https://developer.nylas.com/docs/developer-tools/sdk/node-sdk/upgrade-version-six#create-a-draft-comparison) uses a _different_ property for files, which also type errors.

**To Reproduce**

Create new Draft from example in https://developer.nylas.com/docs/api/#post/drafts > Code Samples > Node SDK.
```
const draft = new Draft(nylas, {
  to: [{ name: 'Nylas Swag', email: 'swag@nylas.com' }],
  subject: 'With Love, From Nylas',
  body: 'This email was sent using the Nylas email API. Visit https://nylas.com for details.',
  fileIdsToAttach: ["file_id_1", "file_id_2"],
  replyToMessageId: '<message_id>'
});
```

Get the following type error:
```
Argument of type '{ to: { name: string; email: string; }[]; subject: string; body: string; fileIdsToAttach: string[]; replyToMessageId: string; }' is not assignable to parameter of type 'DraftProperties'.
  Object literal may only specify known properties, and 'fileIdsToAttach' does not exist in type 'DraftProperties'
```

**Expected behavior**
The Node SDK code sample at https://developer.nylas.com/docs/api/#post/drafts should not have type errors.

Note that I was able to get the email to send with no type errors with the following code:
```
  const nylasDraft = new Draft(nylas, {
    ...
    files: await Promise.all(fileIds?.map((id) => nylas.files.find(id)) ?? []),
  });
```

And while the code sample in the [v6 migration guide](https://developer.nylas.com/docs/developer-tools/sdk/node-sdk/upgrade-version-six#create-a-draft-comparison) has a type error, it seems to send the email properly if you silence the compiler:

```
  const nylasDraft = new Draft(nylas, {
    ...
    files: fileIds?.map((id) =>({id}) as FileProperties),
  });
```

**SDK Version:**
6.3.1

**Comment by mrashed-dev** [comment]
Thanks for opening the issue @ederski! `fileIdsToAttach` is the correct key name, and it exists on the `Draft` class as a property, however it is missing from the `DraftProperties` type! I'll push a fix for this to address your issue. For now as a bypass until the fix is released you can do something like:

```js
const draft = new Draft(nylas, {
  to: [{ name: 'Nylas Swag', email: 'swag@nylas.com' }],
  subject: 'With Love, From Nylas',
  body: 'This email was sent using the Nylas email API. Visit https://nylas.com for details.',
  replyToMessageId: '<message_id>'
});
draft.fileIdsToAttach = ["file_id_1", "file_id_2"],
```

Regarding the v6 migration guide -- it's not incorrect. The property `fileIdsToAttach` is a new property introduced in v6.2.0 after it was requested by a user (#314). Prior to this update, the way to attach files to a `Draft` you would set the `files` property which is of `File[]` type. An example on how this would work is this snippet:

```js
// Read the file and metadata
const fileContents = fs.readFileSync('hello_world.txt', 'utf8');
const fileSize = fs.statSync(filename).size;
fs.unlinkSync(filename);

// Create the `File` object representing the created file
const nylasFile = new File(nylas, {
    filename: 'hello_world.txt',
    data: fileContents,
    contentType: 'text/plain',
    size: fileSize
});

// Upload it to the Nylas API
await nylasFile.upload();

// Create a draft
const draft = new Draft(nylas, {
  to: [{ name: 'Nylas Swag', email: 'swag@nylas.com' }],
  subject: 'With Love, From Nylas',
  body: 'This email was sent using the Nylas email API. Visit https://nylas.com for details.',
  files: [nylasFile],
  replyToMessageId: '<message_id>'
});
```

I will keep you updated for a fix.

**Comment by ederski** [comment]
Hi @mrashed-dev and thanks for the quick update! Sounds like we can use `fileIdsToAttach` once the types are updated :). 

Just wanted to also clarify that while we can also use the `files` property to attach files, it will also type error when used as described in the migration guide: `files: [{ id: '{file_id}' }]`. The `files` property is of type `FileProperty[]` and `FileProperty` does not have an `id` property.

**Comment by mrashed-dev** [comment]
@ederski Thanks for your response! The `files` property in `DraftProperties` accepts a `FileProperties[]` type as you mentioned. We don't include `id` in `*Properties` types because the IDs are uniquely generated on the API side and these `*Properties` types are used for new objects usually, so we aren't expecting a user to fill that ID field in. That's why we introduced `fileIdsToAttach` because it provides a way to just send in file IDs in as a list without having to actually fetch them.

However, since `File` extends `FileProperties` you should be able to assign an array of `File` objects to the `files` property in `DraftProperties`.

**Comment by ederski** [comment]
That sounds fine, I was just trying to point out that the example in the [v6 migration guide](https://developer.nylas.com/docs/developer-tools/sdk/node-sdk/upgrade-version-six#create-a-draft-comparison) is invalid. As you pointed out, it could be corrected in two ways, either:
```
files: [nylas.files.find('{file_id}')]
```
or:
```
fileIdsToAttach: ['{file_id}']
```

**Comment by mrashed-dev** [comment]
@ederski Thank you for your feedback! I'll also pass this along to our internal docs team provide better clarity on this field! Also the fix was just merged into master and is pending release, I'll message you as soon as we have the release out. Thanks for your patience!

**Comment by ederski** [comment]
Thanks so much!

**Comment by mrashed-dev** [comment]
@ederski No problem at all! v6.3.2 is out and it should fix your issue!
