### ISSUE TITLE
Incorrect typing for `Event.originalStartTime`

### ISSUE THREAD

**Issue by mheavenor** [nylas/nylas-nodejs#380]
**Describe the bug**

The typing of the `originalStartTime` property on the `Event` model is typed as a number. The value, however, is an instance of a Date object.

**To Reproduce**

```
const idOfRecurringEvent = "some_id"
const event = await nylas.events.find(idOfRecurringEvent);
console.log(event.originalStartTime instanceof Date) // true even though event.originalStartTime is supposedly a 'number'
```

**Expected behavior**
The typing for `originalStartTime` should be `Date` as that is what the value is

**SDK Version:**
6.4.1
The codebase seems to still type `originalStartTime` as a number as specified here: [https://github.com/nylas/nylas-nodejs/blob/main/src/models/event.ts#L77](https://github.com/nylas/nylas-nodejs/blob/main/src/models/event.ts#L77)

**Comment by mrashed-dev** [comment]
Thanks for opening this issue @mheavenor, we're taking a look and will post an update once we have one.

**Comment by mrashed-dev** [comment]
@mheavenor thanks for your patience! You're correct as it's a typing mismatch, however because replacing `number` with `Date` entirely would result in a breaking change, for now we're going to set the type as a union of those two types and will be released in the next update. Once v7.0 drops (in the works) we will ensure that this attribute will be corrected to just `Date`. Sorry for the inconvenience, and thanks for bringing this to our attention!
