### ISSUE TITLE
Unable to rotate webhook secrets

### ISSUE THREAD

**Issue by Zellotath** [nylas/nylas-nodejs#596]
**Describe the bug**
The `webhooks.rotateSecret` method calls an incorrect endpoint, resulting in the call failing with an error.

```
[error]: Received an error but could not parse response from the server: Cannot POST /v3/webhooks/<webhookId>/rotate-secret
{
  "error": {},
  "requestId": "<requestId>",
  "user": {
    "id": "1",
    "email": "<email>"
  }
}
```

**To Reproduce**
```
const nylas = new Nylas({ apiKey });
const response = await nylasClient.webhooks.rotateSecret({ webhookId }); // -- fails here
```

**Expected behavior**
This method should call the correct endpoint, as defined in the documentation [here](https://developer.nylas.com/docs/api/v3/admin/#post-/v3/webhooks/rotate-secret/-id-):

> `POST /v3/webhooks/rotate-secret/{id}`

**SDK Version:**
7.6.1

**Additional context**
The endpoint described in the documentation works correctly when using an Axios instance to call the endpoint directly.

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have identified the issue in the `rotateSecret` method of the `Webhooks` class. The problem was that it was using the incorrect HTTP method and path. I've updated the method to use the correct POST request to the `/v3/webhooks/rotate-secret/{id}` endpoint as specified in the documentation. Here's what I changed:

I also created pull request: https://github.com/nylas/nylas-nodejs/pull/598


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission
